development:
  user_active_session_duration: 2 #in days
  reset_password_token_duration: 15 #in minutes
  otp_active_duration: 10 #in minutes
 
test:
  user_active_session_duration: 2 #in days
  reset_password_token_duration: 15 #in minutes
  otp_active_duration: 10 #in minutes

production:
  user_active_session_duration: 2 #in days
  reset_password_token_duration: 15 #in minutes
  otp_active_duration: 10 #in minutes
